const multer = require('multer');
const path = require('path');
const maxSize = 5 * 1024 * 1024; // 5MB in bytes

const storage = multer.diskStorage({
    destination: function (req, file, next) {
        next(null, 'public/mappersFiles');
    },
    filename: function (req, file, next) {
        const currentDate = new Date();
        const currentTime = currentDate.toLocaleTimeString().replace(/:/g, '-').replace(/\s/g, '');
        let name = currentDate.getTime() + '-' + currentTime + '-' + file.originalname.split('.')[0];
        const fileExtension = path.extname(file.originalname);

        // Check if the file extension is either .csv or .xlsx
        if (fileExtension !== '.csv' && fileExtension !== '.xlsx') {
            return next(new Error('File must be either .csv or .xlsx'));
        }

        // Use the filename generated by Multer with the dynamic extension
        const filename = name + fileExtension;


        next(null, filename);
    },
});

const upload = multer({
    storage: storage,
    limits: { fileSize: maxSize },
})

module.exports = upload;