name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build, tag, and push image to ECR
        env:
          ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
        run: |
          # Build the Docker image
          docker build -t $ECR_REPOSITORY_URI:latest .

          # Tag the Docker image
          docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:latest

          # Push the Docker image to ECR
          docker push $ECR_REPOSITORY_URI:latest
